ShivGardenHouse/Models/SMS.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data;
using System.Data.SqlClient;

namespace ShivGardenHouse.Models
{
    public class SMS:Common
    {
        public string TemplateName { get; set; }
        public string PK_TemplateId { get; set; }
        public string Msg { get; set; }
        public List<SMS> ListSMSTemplate { get; set; }
        public string MessageCount { get; set; }
        public string TotalSMS { get; set; }
        public string PK_SendSMSId { get; set; }
        public string AssocCustom { get; set; }
        public List<SMS> lstsmsdata { get; set; }
        public string FirstName { get; set; }
        public string LoginId { get; set; }
        public string PK_UserId { get; set; }
        public string PK_RoleId { get; set; }
        public string Mobile { get; set; }
        public DataTable dtSMS { get; set; }
        public string TemplateNameText { get; set; }

        #region SMSTemplate
        public DataSet SavingSMSTemplate()
        {
            SqlParameter[] para =
            {
                new SqlParameter("@AddedBy",AddedBy),
                new SqlParameter("@TemplateName",TemplateName),
                new SqlParameter("@Msg",Msg)
            };
            DataSet ds = Connection.ExecuteQuery("SMSTemplate", para);
            return ds;
        }

        public DataSet GettingSMSTemplate()
        {
            SqlParameter[] para =
            {
                new SqlParameter("@PK_TemplateId",PK_TemplateId)
            };
            DataSet ds = Connection.ExecuteQuery("SMSTemplateList", para);
            return ds;
        }

        public DataSet UpdatingSMSTemplate()
        {
            SqlParameter[] para =
            {
                new SqlParameter("@UpdatedBy",UpdatedBy),
                new SqlParameter("@TemplateName",TemplateName),
                new SqlParameter("@Msg",Msg),
                new SqlParameter("@PK_TemplateId",PK_TemplateId)
            };
            DataSet ds = Connection.ExecuteQuery("UpdateSMSTemplate", para);
            return ds;
        }

        public DataSet DeletingSMSTemplate()
        {
            SqlParameter[] para =
            {
                new SqlParameter("@DeletedBy",AddedBy),
                new SqlParameter("@PK_TemplateId",PK_TemplateId)
            };
            DataSet ds = Connection.ExecuteQuery("DeleteSMSTemplate", para);
            return ds;
        }


        #endregion

        #region SendSMS

        public DataSet GetSMSData()
        {
            SqlParameter[] para =
            {
                new SqlParameter("@AssocCustom",AssocCustom)
            };
            DataSet ds = Connection.ExecuteQuery("SMSData", para);
            return ds;
        }

        public DataSet SaveSMSData()
        {
            SqlParameter[] para ={
                                   new SqlParameter("@dtSMS",dtSMS),
                                   new SqlParameter("@Message", Msg),
                                   new SqlParameter("@SMSCount",TotalSMS),
                                   new SqlParameter("@AddedBy",AddedBy),
                                   new SqlParameter("@MessageTemplate",TemplateNameText),
                               };
            DataSet ds = Connection.ExecuteQuery("SaveSMSReport", para);
            return ds;
        }

        #endregion
    }
}

ShivGardenHouse/Controllers/AdminReportsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ShivGardenHouse.Filter;
using ShivGardenHouse.Models;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace ShivGardenHouse.Controllers
{
    public class AdminReportsController : AdminBaseController
    {
        //
        // GET: /Reports/

        public ActionResult Reports()
        {
            return View();
        }

        #region CustomerLedgerReport
        public ActionResult CustomerLedgerReport(string PK_BookingId)
        {

            Plot model = new Plot();
            model.SiteID = model.SiteID == "0" ? null : model.SiteID;
            model.SectorID = model.SectorID == "0" ? null : model.SectorID;
            model.PlotNumber = string.IsNullOrEmpty(model.PlotNumber) ? null : model.PlotNumber;
            model.BlockID = model.BlockID == "0" ? null : model.BlockID;
            model.PK_BookingId = PK_BookingId;
            DataSet dsBookingDetails = model.GetBookingDetailsList();
            #region ddlSite
            int count1 = 0;
            List<SelectListItem> ddlSite = new List<SelectListItem>();
            DataSet dsSite = model.GetSiteList();
            if (dsSite != null && dsSite.Tables.Count > 0 && dsSite.Tables[0].Rows.Count > 0)
            {
                foreach (DataRow r in dsSite.Tables[0].Rows)
                {
                    if (count1 == 0)
                    {
                        ddlSite.Add(new SelectListItem { Text = "Select Site", Value = "0" });
                    }
                    ddlSite.Add(new SelectListItem { Text = r["SiteName"].ToString(), Value = r["PK_SiteID"].ToString() });
                    count1 = count1 + 1;

                }
            }
            ViewBag.ddlSite = ddlSite;
            #endregion

            List<SelectListItem> ddlSector = new List<SelectListItem>();
            ddlSector.Add(new SelectListItem { Text = "Select Sector", Value = "0" });
            ViewBag.ddlSector = ddlSector;

            List<SelectListItem> ddlBlock = new List<SelectListItem>();
            ddlBlock.Add(new SelectListItem { Text = "Select Block", Value = "0" });
            ViewBag.ddlBlock = ddlBlock;
            return View(model);
        }

        public ActionResult Details(string BookingNumber, string SiteID, string SectorID, string BlockID, string PlotNumber)
        {
            Plot model = new Plot();
            try
            {
                List<Plot> lst = new List<Plot>();
                model.SiteID = SiteID == "0" ? null : SiteID;
                model.SectorID = SectorID == "0" ? null : SectorID;
                model.BlockID = BlockID == "0" ? null : BlockID;
                model.BookingNumber = string.IsNullOrEmpty(BookingNumber) ? null : BookingNumber;
                model.PlotNumber = string.IsNullOrEmpty(PlotNumber) ? null : PlotNumber;
                // model.PlotNumber = PlotNumber;
                DataSet dsblock = model.FillDetails();
                if (dsblock != null && dsblock.Tables[0].Rows.Count > 0)
                {

                    if (dsblock.Tables[0].Rows[0]["MSG"].ToString() == "0")
                    {
                        model.Result = dsblock.Tables[0].Rows[0]["ErrorMessage"].ToString();
                    }
                    else if (dsblock.Tables[0].Rows[0]["MSG"].ToString() == "1")
                    {

                        model.Result = "yes";
                        model.hdBookingNo = Crypto.Encrypt(dsblock.Tables[0].Rows[0]["BookingNo"].ToString());
                        // model.PlotID = dsblock.Tables[0].Rows[0]["PK_PlotID"].ToString();
                        model.PlotAmount = dsblock.Tables[0].Rows[0]["PlotAmount"].ToString();
                        model.ActualPlotRate = dsblock.Tables[0].Rows[0]["ActualPlotRate"].ToString();
                        model.PlotRate = dsblock.Tables[0].Rows[0]["PlotRate"].ToString();
                        model.PayAmount = dsblock.Tables[0].Rows[0]["PaidAmount"].ToString();
                        model.BookingDate = dsblock.Tables[0].Rows[0]["BookingDate"].ToString();
                        model.BookingAmount = dsblock.Tables[0].Rows[0]["BookingAmt"].ToString();
                        model.PaymentDate = dsblock.Tables[0].Rows[0]["PaymentDate"].ToString();
                        model.PaidAmount = dsblock.Tables[0].Rows[0]["PaidAmount"].ToString();
                        model.Discount = dsblock.Tables[0].Rows[0]["Discount"].ToString();
                        model.PaymentPlanID = dsblock.Tables[0].Rows[0]["Fk_PlanId"].ToString();
                        model.PlanName = dsblock.Tables[0].Rows[0]["PlanName"].ToString();
                        model.PK_BookingId = dsblock.Tables[0].Rows[0]["PK_BookingId"].ToString();
                        model.TotalAllotmentAmount = dsblock.Tables[0].Rows[0]["TotalAllotmentAmount"].ToString();
                        model.PaidAllotmentAmount = dsblock.Tables[0].Rows[0]["PaidAllotmentAmount"].ToString();
                        model.BalanceAllotmentAmount = dsblock.Tables[0].Rows[0]["BalanceAllotmentAmount"].ToString();
                        model.TotalInstallment = dsblock.Tables[0].Rows[0]["TotalInstallment"].ToString();
                        model.InstallmentAmount = dsblock.Tables[0].Rows[0]["InstallmentAmount"].ToString();
                        model.PlotArea = dsblock.Tables[0].Rows[0]["PlotArea"].ToString();
                        model.Balance = dsblock.Tables[0].Rows[0]["BalanceAmount"].ToString();

                        if (dsblock != null && dsblock.Tables.Count > 0 && dsblock.Tables[1].Rows.Count > 0)
                        {
                            foreach (DataRow r in dsblock.Tables[1].Rows)
                            {
                                Plot obj = new Plot();

                                obj.PK_BookingDetailsId = r["PK_BookingDetailsId"].ToString();
                                obj.PK_BookingId = r["Fk_BookingId"].ToString();
                                obj.InstallmentNo = r["InstallmentNo"].ToString();
                                obj.InstallmentDate = r["InstallmentDate"].ToString();
                                obj.PaymentDate = r["PaymentDate"].ToString();
                                obj.PaidAmount = r["PaidAmount"].ToString();
                                obj.InstallmentAmount = r["InstAmt"].ToString();
                                obj.PaymentMode = r["PaymentModeName"].ToString();
                                obj.DueAmount = r["DueAmount"].ToString();

                                lst.Add(obj);
                            }
                            model.lstPlot = lst;
                        }
                    }
                }
                else
                {
                    model.Result = "No record found !";
                }


                #region ddlSite
                int count1 = 0;
                Master objmaster = new Master();
                List<SelectListItem> ddlSite = new List<SelectListItem>();
                DataSet dsSite = objmaster.GetSiteList();
                if (dsSite != null && dsSite.Tables.Count > 0 && dsSite.Tables[0].Rows.Count > 0)
                {
                    foreach (DataRow r in dsSite.Tables[0].Rows)
                    {
                        if (count1 == 0)
                        {
                            ddlSite.Add(new SelectListItem { Text = "Select Site", Value = "0" });
                        }
                        ddlSite.Add(new SelectListItem { Text = r["SiteName"].ToString(), Value = r["PK_SiteID"].ToString() });
                        count1 = count1 + 1;

                    }
                }
                ViewBag.ddlSite = ddlSite;
                #endregion

                #region GetSectors
                List<SelectListItem> ddlSector = new List<SelectListItem>();
                DataSet dsSector = objmaster.GetSectorList();
                int sectorcount = 0;

                if (dsSector != null && dsSector.Tables.Count > 0)
                {

                    foreach (DataRow r in dsSector.Tables[0].Rows)
                    {
                        if (sectorcount == 0)
                        {
                            ddlSector.Add(new SelectListItem { Text = "Select Sector", Value = "0" });
                        }
                        ddlSector.Add(new SelectListItem { Text = r["SectorName"].ToString(), Value = r["PK_SectorID"].ToString() });
                        sectorcount = 1;
                    }
                }

                ViewBag.ddlSector = ddlSector;
                #endregion

                #region BlockList
                List<SelectListItem> lstBlock = new List<SelectListItem>();

                int blockcount = 0;
                //objmodel.SiteID = ds.Tables[0].Rows[0]["PK_SiteID"].ToString();
                //objmodel.SectorID = ds.Tables[0].Rows[0]["PK_SectorID"].ToString();
                DataSet dsblock1 = objmaster.GetBlockList();


                if (dsblock1 != null && dsblock1.Tables.Count > 0 && dsblock1.Tables[0].Rows.Count > 0)
                {

                    foreach (DataRow dr in dsblock1.Tables[0].Rows)
                    {
                        if (blockcount == 0)
                        {
                            lstBlock.Add(new SelectListItem { Text = "Select Block", Value = "0" });
                        }
                        lstBlock.Add(new SelectListItem { Text = dr["BlockName"].ToString(), Value = dr["PK_BlockID"].ToString() });
                        blockcount = 1;
                    }

                }


                ViewBag.ddlBlock = lstBlock;
                #endregion
            }
            catch (Exception ex)
            {
                model.Result = ex.Message;
            }

ShivGardenHouse/Views/AdminReports/DistributePayment.cshtml
@model ShivGardenHouse.Models.AssociateBooking

@{
    ViewBag.Title = "DistributePayment";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}


@using (Html.BeginForm("DistributePayment", "AdminReports", FormMethod.Post, new { @id = "form1" }))
{


    <div class="page-header">
        <div class="page-block">
            <div class="row align-items-center">
                <div class="col-md-8">
                    <div class="page-header-title">
                        <h4 class="m-b-10">Distribute Payment</h4>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <div class="pcoded-inner-content">
        <div class="main-body">
            <div class="page-wrapper">
                <div class="page-body">
                    <div class="row">
                        <p style="color: red">
                            @TempData["distributed"]
                        </p>
                        <div class="col-md-12">
                            <!-- HTML5 Export Buttons table start -->
                            <div class="card">
                                @*<div class="card-header table-card-header">
                                        <a class="btn btn-primary btn-sm" style="margin-left:75%" href="/Master/NewsMaster">Add New</a>
                                    </div>*@
                                <div class="card-block">
                                    <div class="row">


                                        <div class="col-md-2">
                                            <div class="form-group">
                                                Date
                                                @Html.TextBoxFor(m => m.ToDate, new { @class = "form-control", @readonly = "ds" })
                                            </div>
                                        </div>

                                        <div class="col-md-2">
                                            <div class="form-group">
                                                <br />
                                                <input class="btn btn-success" type="submit" value="Distribute" id="btnSave" name="Save" onclick="return validateform();" />
                                            </div>
                                        </div>
                                    </div>
                                    <div class="dt-responsive table-responsive">
                                        <table id="basic-btn" class="table table-striped table-bordered nowrap">
                                            <thead>
                                                <tr>
                                                    <th>S No.</th>
                                                    <th>Login Id</th>
                                                    <th>Associate Name</th>
                                                    <th>Income</th>

                                                </tr>
                                            </thead>
                                            <tbody>
                                                @if (Model != null)
                                                {
                                                    if (Model.lstPlot != null)
                                                    {
                                                        int i = 1;
                                                        foreach (var Item in Model.lstPlot)
                                                        {
                                                            <tr class="text-left">
                                                                <td>@i</td>
                                                                <td>@Item.ToID</td>
                                                                <td>@Item.ToName</td>
                                                                <td>@Item.Income</td>

                                                            </tr>

                                                            i++;
                                                        }
                                                    }
                                                }

                                            </tbody>
                                            <tfoot>
                                                <tr>
                                                    <th>S No.</th>
                                                    <th>Login Id</th>
                                                    <th>Associate Name</th>
                                                    <th>Income</th>
                                                </tr>
                                            </tfoot>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

}


<script src="~/files/bower_components/jquery/js/jquery.min.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link rel="stylesheet" type="text/css" href="https://code.jquery.com/ui/1.12.0/themes/smoothness/jquery-ui.css">
<script>


    $('#ToDate').datepicker({
        dateFormat: 'dd/mm/yy',
        changeYear: true,
        changeMonth: true,
        //minDate: 0
    });

    function validateform() {
        $(".errortext").removeClass("errortext");

        if ($('#ToDate').val() == '') {
            $("#ToDate").addClass('errortext');
            $('#ToDate').focus();
            return false;
        }



        return true;
    }
</script>



<style>
    .errortext {
        border: 1px solid red !important;
        background-color: #fff0f0 !important;
    }
</style>

ShivGardenHouse/Views/AdminReports/PayoutDetails.cshtml
@model ShivGardenHouse.Models.AssociateBooking

@{
    ViewBag.Title = "PayoutDetails";
    Layout = "~/Views/Shared/AdminLayout.cshtml";
}



@using (Html.BeginForm("PayoutDetails", "AdminReports", FormMethod.Post, new { @id = "form1" }))
{


    <div class="page-header">
        <div class="page-block">
            <div class="row align-items-center">
                <div class="col-md-8">
                    <div class="page-header-title">
                        <h4 class="m-b-10">Payout Details</h4>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <div class="pcoded-inner-content">
        <div class="main-body">
            <div class="page-wrapper">
                <div class="page-body">
                    <div class="row">
                        <div class="col-md-12">
                            <!-- HTML5 Export Buttons table start -->
                            <div class="card">
                                <div class="card-header table-card-header">

                                </div>
                                <div class="card-block">
                                    <div class="row">
                                        <div class="col-md-2">
                                            <div class="form-group">
                                                Login ID
                                                @Html.TextBoxFor(m => m.UserID, new { @class = "form-control", @Placeholder = "Search by Login ID" })
                                            </div>
                                        </div>
                                        <div class="col-md-2">
                                            <div class="form-group">
                                                PayOut No.
                                                @Html.TextBoxFor(m => m.PayOutNo, new { @class = "form-control", @Placeholder = "Search by PayOutNo" })
                                            </div>
                                        </div>
                                        <div class="col-md-2">
                                            <div class="form-group">
                                                From Date
                                                @Html.TextBoxFor(m => m.FromDate, new { @class = "form-control", @readonly = "ds" })
                                            </div>
                                        </div>
                                        <div class="col-md-2">
                                            <div class="form-group">
                                                To Date
                                                @Html.TextBoxFor(m => m.ToDate, new { @class = "form-control", @readonly = "ds" })
                                            </div>
                                        </div>

                                        <div class="col-md-2">
                                            <div class="form-group">
                                                <br />
                                                <input class="btn btn-success" type="submit" value="Search" id="btnSearch" name="Search" />
                                            </div>
                                        </div>
                                    </div>
                                    <div class="dt-responsive table-responsive">
                                        <table id="basic-btn" class="table table-striped table-bordered nowrap">
                                            <thead>
                                                <tr>
                                                    <th>S No.</th>
                                                    <th> Closing Date</th>
                                                    <th> PayOut No</th>
                                                    <th>  Login ID</th>
                                                    <th> First Name</th>
                                                    <th> Gross Amount</th>
                                                    <th> TDS</th>
                                                    <th> Processing</th>
                                                    <th> NetAmount</th>
                                                    <th>Action</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                @if (Model != null)
                                                {
                                                    if (Model.lstPlot != null)
                                                    {
                                                        int i = 1;
                                                        foreach (var Item in Model.lstPlot)
                                                        {
                                                            <tr class="text-left">
                                                                <td>@i</td>
                                                                <td>@Item.ClosingDate</td>
                                                                <td>@Item.PayOutNo</td>
                                                                <td>@Item.AssociateLoginID  </td>
                                                                <td>@Item.FirstName </td>
                                                                <td>@Item.GrossAmount</td>
                                                                <td>@Item.TDS</td>
                                                                <td>@Item.Processing</td>
                                                                <td>@Item.NetAmount</td>
                                                                <td>
                                                                    @*<a href="/Reports/PrintAllotment?PK_BookingId=@Item.PK_BookingId" class="btn btn-primary btn-sm" type="submit" name="Print" >Print</a>*@
                                                                    <a href="/AdminReports/ClosingWisePayoutDetails?PK_PaidPayoutId=@Item.PK_PaidPayoutId" class="btn btn-success btn-sm" target="_blank">Print</a>
                                                                </td>
                                                            </tr>
                                                            i++;
                                                        }
                                                    }
                                                }

                                            </tbody>
                                            <tfoot>
                                                <tr>
                                                    <th>S No.</th>
                                                    <th> Closing Date</th>
                                                    <th> PayOut No</th>
                                                    <th>  Login ID</th>
                                                    <th> First Name</th>
                                                    <th> Gross Amount</th>
                                                    <th> TDS</th>
                                                    <th> Processing</th>
                                                    <th> NetAmount</th>
                                                    <th>Action</th>
                                                </tr>
                                            </tfoot>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


}



<script src="~/files/bower_components/jquery/js/jquery.min.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link rel="stylesheet" type="text/css" href="https://code.jquery.com/ui/1.12.0/themes/smoothness/jquery-ui.css">
<script>

    $('#FromDate').datepicker({
        dateFormat: 'dd/mm/yy',
        changeYear: true,
        changeMonth: true,
    });
    $('#ToDate').datepicker({
        dateFormat: 'dd/mm/yy',
        changeYear: true,
        changeMonth: true,
    });

</script>

ShivGardenHouse/Views/AdminReports/PrintWelcomeLetter.cshtml
@model ShivGardenHouse.Models.TraditionalAssociate
@{
    Layout = null;
}

<!DOCTYPE html>


<html>
<head>
    <title>PrintAllotment</title>
    <style>
        table, th, td {
            font-size: medium;
            border: 1px solid black;
            border-collapse: collapse;
        }

        th, td {
            font-size: medium;
            padding: 5px;
        }
    </style>

</head>
<body>
    <div style="border: 1px solid;padding: 15px;">
        <table style="border: 0px none black;">
            <tr style="border: 0px none black;">
                <td style="border: 0px none black;">
                    <img src="../../Website/images/Logo.png" />
                </td>
                <td style="border: 0px none black;"></td>

                <td style="border: 0px none black;"><h1>Shiv Garden House Projects </h1></td>
            </tr>

        </table>
        <br />
        <table style="border: 0px none black;">
            <tr style="border: 0px none black;">
                <td colspan="2" style="border: 0px none black;">
                    Dear <b>@ViewBag.AssociateName,</b>

                    <p>
                        Welcome to our valued family of @ViewBag.CompanyName ,Thank you
                        for joining hand with us.It is the people like you who make
                        being in business such a pleasure.Our Business is source
                        of Pride to us and with partners like you,we find going to
                        work each day rewarding experience.
                    </p>
                </td>


                <td style="border: 0px none black;"><img src="@ViewBag.ProfilePic" style="height:130px;width:130px;border: 1px solid black;" /></td>
            </tr>

        </table>
        <br />

        <table style="width: 100%;">
            <tr>
                <td><b>Associate Id:    </b> </td>
                <td>@ViewBag.AssociateID </td>
                <td><b>Associate Name:    </b>  </td>
                <td>@ViewBag.AssociateName</td>
                <td><b>Mobile     </b></td>
                <td>@ViewBag.Contact</td>
            </tr>

            <tr>
                <td><b>Rank:    </b></td>
                <td>@ViewBag.Designation</td>

                <td><b>City:    </b></td>
                <td>@ViewBag.City</td>
                <td><b>A/C NO.:    </b></td>
                <td>@ViewBag.MemberAccNo</td>
            </tr>
            <tr>

                <td><b>Bank:    </b></td>
                <td>@ViewBag.MemberBankName</td>
                <td><b>Branch:    </b></td>
                <td>@ViewBag.MemberBranch</td>
                <td><b>IFSC Code.:    </b></td>
                <td>@ViewBag.IFSCCode</td>
            </tr>
            <tr>
                <td><b>Address:    </b></td>
                <td colspan="5">@ViewBag.Address</td>

            </tr>
        </table>
        <br />
        <br />
        <div>
            We value the comments the our Associate's on receipt of
            this letter we hope you will share your Vulnerable
            thoughts with us.Please accept our best wishes for your
            continuous prosperity and good health.
            <br />
            <br />
            With Regards,
            <br />

            @ViewBag.CompanyName
        </div>
        

    </div>
</body>
</html>